frontend:
  build: .
  volumes:
    - ./:/usr/src/app
  environment:
    - 'VIRTUAL_HOST=http://*/*, https://*/*'
    - VIRTUAL_HOST_WEIGHT=1
  ports:
    - 4200:80
    - 49153:49153
    - 8080:8080
  command:  bash -c "npm run prebuild:prod && npm run build:prod"
