frontend:
  build: .
  volumes:
    - ./src:/usr/src/app/src
  environment:
    - 'VIRTUAL_HOST=http://*/*, https://*/*'
    - VIRTUAL_HOST_WEIGHT=1
  ports:
    - 4200:80
    - 49153:49153
  command:  bash -c "cd /var/www && npm run prebuild:prod && npm run build:prod"
